/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package devindow.GeoMeasure;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int distanceFeet=0x7f050007;
        public static final int distanceKm=0x7f050004;
        public static final int distanceMiles=0x7f050005;
        public static final int distanceYards=0x7f050006;
        public static final int measureFromHereTo=0x7f050002;
        public static final int name=0x7f050000;
        public static final int ok=0x7f050001;
        public static final int spinnerTo=0x7f050003;
    }
    public static final class layout {
        public static final int input_dialog=0x7f030000;
        public static final int locations_row=0x7f030001;
        public static final int main=0x7f030002;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
}
